(load #P"~/quicklisp/setup.lisp")
(require 'asdf)
(in-package :cl-user)
(defun reload ()
  (asdf:operate 'asdf:load-op :mudibifasy)
  (in-package :md))
(reload)
(print "Welcome to MuDiBiFaSy, this an interactive lisp shell, type (help) for the list of instructions")
(in-package :md)
